import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "gu" | "mr" | "ta" | "te" | "ml" | "pa" | "ur" | "kn" | "bn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.alerts": "Alerts",
    "nav.analytics": "Analytics",
    "nav.prediction": "AI Prediction",
    "nav.settings": "Settings",
    
    // Dashboard
    "dashboard.title": "GrainGuard Dashboard",
    "dashboard.subtitle": "Real-time monitoring of grain storage conditions",
    "dashboard.bluetooth.connected": "Bluetooth Connected",
    "dashboard.sensors.title": "Sensor Readings",
    "dashboard.status.overview": "Status Overview",
    "dashboard.status.all_systems": "All systems operational",
    "dashboard.status.check_alerts": "Check alerts for details",
    "dashboard.last_updated": "Last updated",
    
    // Sensors
    "sensor.temperature": "Temperature",
    "sensor.humidity": "Humidity",
    "sensor.gas": "Gas Level",
    "sensor.vibration": "Vibration",
    "sensor.status.safe": "🟢 Safe",
    "sensor.status.warning": "🟡 Warning",
    "sensor.status.danger": "🔴 Danger",
    "sensor.temp.optimal": "Optimal range",
    "sensor.temp.high": "Above threshold",
    "sensor.humidity.optimal": "Optimal range",
    "sensor.humidity.high": "Above threshold",
    "sensor.gas.normal": "Normal levels",
    "sensor.gas.elevated": "Elevated levels detected",
    "sensor.vibration.stable": "Stable",
    "sensor.vibration.detected": "Activity detected",
    
    // Voice Assistant
    "voiceAssistant": "Voice Assistant",
    "voiceListening": "Listening...",
    "voiceListeningDesc": "Start speaking",
    "voiceError": "Error",
    "voiceMicError": "Could not access microphone",
    "voiceProcessError": "Error processing audio",
    "voiceStop": "Stop",
    "voiceYouSaid": "You said",
    "voiceAssistantReply": "Assistant's reply",
    "voiceAssistantDesc": "Press the microphone button and ask something about your grain storage",
    
    // Alerts
    "alerts.title": "Alerts",
    "alerts.subtitle": "Recent notifications and warnings",
    "alerts.no_alerts": "No alerts at the moment",
    "alerts.type.info": "Info",
    "alerts.type.warning": "Warning",
    "alerts.type.danger": "Danger",
    "alerts.type.prediction": "AI Prediction",
    
    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "Historical data and trends",
    "analytics.temp_humidity": "Temperature & Humidity",
    "analytics.temp_humidity.desc": "Last 24 hours",
    "analytics.gas": "Gas Levels",
    "analytics.gas.desc": "Parts per million (ppm)",
    "analytics.vibration": "Vibration Activity",
    "analytics.vibration.desc": "Movement detection",
    
    // Prediction
    "prediction.title": "AI-Driven Spoilage Risk Analysis",
    "prediction.subtitle": "Predictive analytics for grain quality",
    "prediction.confidence": "Confidence",
    "prediction.risk": "Risk Assessment",
    "prediction.risk.low": "Low Risk",
    "prediction.risk.medium": "Medium Risk",
    "prediction.risk.high": "High Risk",
    "prediction.factors": "Key Contributing Factors",
    "prediction.actions": "Recommended Actions",
    "prediction.action.inspect": "Inspect Storage",
    "prediction.action.ventilate": "Increase Ventilation",
    "prediction.action.monitor": "Monitor Closely",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Configure thresholds and notifications",
    "settings.thresholds": "Safety Thresholds",
    "settings.temp.max": "Maximum Temperature (°C)",
    "settings.temp.min": "Minimum Temperature (°C)",
    "settings.temp.alert": "Alert when temperature exceeds this value",
    "settings.humidity.max": "Maximum Humidity (%)",
    "settings.humidity.min": "Minimum Humidity (%)",
    "settings.gas.max": "Maximum Gas Level (ppm)",
    "settings.vibration.max": "Maximum Vibration",
    "settings.notifications": "Notifications",
    "settings.notifications.push": "Push Notifications",
    "settings.notifications.push.desc": "Receive alerts on your device",
    "settings.notifications.voice": "Voice Alerts",
    "settings.notifications.voice.desc": "Enable audio notifications for critical alerts",
    "settings.notifications.sms": "SMS Notifications",
    "settings.notifications.sms.desc": "Send text messages for urgent alerts",
    "settings.notifications.ai": "AI Prediction Alerts",
    "settings.notifications.ai.desc": "Notify when AI detects spoilage risk",
    "settings.connection": "Connection",
    "settings.connection.type": "Connection Type",
    "settings.language": "Language",
    "settings.language.select": "Select Language",
    "settings.save": "Save Settings",
    "settings.reset": "Reset to Default",
    
    // Bluetooth
    "bluetooth.title": "Bluetooth Sensor",
    "bluetooth.scan": "Scan for Sensors",
    "bluetooth.disconnect": "Disconnect",
    "bluetooth.status.searching": "Searching for sensors...",
    "bluetooth.status.connected": "Connected to",
    "bluetooth.status.disconnected": "Not connected",
    "bluetooth.unsupported": "Bluetooth not supported in this browser",
  },
  hi: {
    // Navigation
    "nav.dashboard": "डैशबोर्ड",
    "nav.alerts": "चेतावनी",
    "nav.analytics": "विश्लेषण",
    "nav.prediction": "एआई पूर्वानुमान",
    "nav.settings": "सेटिंग्स",
    
    // Dashboard
    "dashboard.title": "ग्रेनगार्ड डैशबोर्ड",
    "dashboard.subtitle": "अनाज भंडारण स्थितियों की रीयल-टाइम निगरानी",
    "dashboard.bluetooth.connected": "ब्लूटूथ कनेक्टेड",
    "dashboard.sensors.title": "सेंसर रीडिंग",
    "dashboard.status.overview": "स्थिति अवलोकन",
    "dashboard.status.all_systems": "सभी सिस्टम सामान्य",
    "dashboard.status.check_alerts": "विवरण के लिए चेतावनी देखें",
    "dashboard.last_updated": "अंतिम अपडेट",
    
    // Sensors
    "sensor.temperature": "तापमान",
    "sensor.humidity": "आर्द्रता",
    "sensor.gas": "गैस स्तर",
    "sensor.vibration": "कंपन",
    "sensor.status.safe": "🟢 सुरक्षित",
    "sensor.status.warning": "🟡 चेतावनी",
    "sensor.status.danger": "🔴 खतरा",
    "sensor.temp.optimal": "इष्टतम सीमा",
    "sensor.temp.high": "सीमा से ऊपर",
    "sensor.humidity.optimal": "इष्टतम सीमा",
    "sensor.humidity.high": "सीमा से ऊपर",
    "sensor.gas.normal": "सामान्य स्तर",
    "sensor.gas.elevated": "उच्च स्तर का पता चला",
    "sensor.vibration.stable": "स्थिर",
    "sensor.vibration.detected": "गतिविधि का पता चला",
    
    // Voice Assistant
    "voiceAssistant": "ध्वनि सहायक",
    "voiceListening": "सुन रहा है...",
    "voiceListeningDesc": "बोलना शुरू करें",
    "voiceError": "त्रुटि",
    "voiceMicError": "माइक्रोफ़ोन एक्सेस नहीं मिल सका",
    "voiceProcessError": "ऑडियो प्रोसेस करने में त्रुटि",
    "voiceStop": "रोकें",
    "voiceYouSaid": "आपने कहा",
    "voiceAssistantReply": "सहायक का जवाब",
    "voiceAssistantDesc": "माइक्रोफ़ोन बटन दबाएं और अपने अनाज भंडारण के बारे में कुछ पूछें",
    
    // Alerts
    "alerts.title": "चेतावनी",
    "alerts.subtitle": "हाल की सूचनाएं और चेतावनियां",
    "alerts.no_alerts": "फिलहाल कोई चेतावनी नहीं",
    "alerts.type.info": "जानकारी",
    "alerts.type.warning": "चेतावनी",
    "alerts.type.danger": "खतरा",
    "alerts.type.prediction": "एआई पूर्वानुमान",
    
    // Analytics
    "analytics.title": "विश्लेषण",
    "analytics.subtitle": "ऐतिहासिक डेटा और रुझान",
    "analytics.temp_humidity": "तापमान और आर्द्रता",
    "analytics.temp_humidity.desc": "पिछले 24 घंटे",
    "analytics.gas": "गैस स्तर",
    "analytics.gas.desc": "पार्ट्स प्रति मिलियन (पीपीएम)",
    "analytics.vibration": "कंपन गतिविधि",
    "analytics.vibration.desc": "गति का पता लगाना",
    
    // Prediction
    "prediction.title": "एआई-संचालित खराब होने का जोखिम विश्लेषण",
    "prediction.subtitle": "अनाज गुणवत्ता के लिए पूर्वानुमानात्मक विश्लेषण",
    "prediction.confidence": "विश्वास",
    "prediction.risk": "जोखिम मूल्यांकन",
    "prediction.risk.low": "कम जोखिम",
    "prediction.risk.medium": "मध्यम जोखिम",
    "prediction.risk.high": "उच्च जोखिम",
    "prediction.factors": "मुख्य योगदान करने वाले कारक",
    "prediction.actions": "अनुशंसित कार्य",
    "prediction.action.inspect": "भंडारण की जांच करें",
    "prediction.action.ventilate": "वेंटिलेशन बढ़ाएं",
    "prediction.action.monitor": "बारीकी से निगरानी करें",
    
    // Settings
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "सीमा और सूचनाएं कॉन्फ़िगर करें",
    "settings.thresholds": "सुरक्षा सीमा",
    "settings.temp.max": "अधिकतम तापमान (°C)",
    "settings.temp.min": "न्यूनतम तापमान (°C)",
    "settings.temp.alert": "जब तापमान इस मान से अधिक हो तो चेतावनी दें",
    "settings.humidity.max": "अधिकतम आर्द्रता (%)",
    "settings.humidity.min": "न्यूनतम आर्द्रता (%)",
    "settings.gas.max": "अधिकतम गैस स्तर (पीपीएम)",
    "settings.vibration.max": "अधिकतम कंपन",
    "settings.notifications": "सूचनाएं",
    "settings.notifications.push": "पुश सूचनाएं",
    "settings.notifications.push.desc": "अपने डिवाइस पर चेतावनी प्राप्त करें",
    "settings.notifications.voice": "वॉयस अलर्ट",
    "settings.notifications.voice.desc": "महत्वपूर्ण चेतावनियों के लिए ऑडियो सूचनाएं सक्षम करें",
    "settings.notifications.sms": "एसएमएस सूचनाएं",
    "settings.notifications.sms.desc": "तत्काल चेतावनियों के लिए टेक्स्ट संदेश भेजें",
    "settings.notifications.ai": "एआई पूर्वानुमान चेतावनी",
    "settings.notifications.ai.desc": "जब एआई खराब होने का जोखिम पता लगाए तो सूचित करें",
    "settings.connection": "कनेक्शन",
    "settings.connection.type": "कनेक्शन प्रकार",
    "settings.language": "भाषा",
    "settings.language.select": "भाषा चुनें",
    "settings.save": "सेटिंग्स सहेजें",
    "settings.reset": "डिफ़ॉल्ट पर रीसेट करें",
    
    // Bluetooth
    "bluetooth.title": "ब्लूटूथ सेंसर",
    "bluetooth.scan": "सेंसर स्कैन करें",
    "bluetooth.disconnect": "डिस्कनेक्ट करें",
    "bluetooth.status.searching": "सेंसर खोज रहे हैं...",
    "bluetooth.status.connected": "कनेक्टेड",
    "bluetooth.status.disconnected": "कनेक्टेड नहीं",
    "bluetooth.unsupported": "इस ब्राउज़र में ब्लूटूथ समर्थित नहीं है",
  },
  gu: {
    // Navigation
    "nav.dashboard": "ડેશબોર્ડ",
    "nav.alerts": "ચેતવણીઓ",
    "nav.analytics": "વિશ્લેષણ",
    "nav.prediction": "એઆઈ આગાહી",
    "nav.settings": "સેટિંગ્સ",
    
    // Dashboard
    "dashboard.title": "ગ્રેઇનગાર્ડ ડેશબોર્ડ",
    "dashboard.subtitle": "અનાજ સંગ્રહ પરિસ્થિતિઓનું રીઅલ-ટાઇમ મોનિટરિંગ",
    "dashboard.bluetooth.connected": "બ્લૂટૂથ કનેક્ટેડ",
    "dashboard.sensors.title": "સેન્સર રીડિંગ્સ",
    "dashboard.status.overview": "સ્થિતિ વિહંગાવલોકન",
    "dashboard.status.all_systems": "બધી સિસ્ટમો કાર્યરત છે",
    "dashboard.status.check_alerts": "વિગતો માટે ચેતવણીઓ તપાસો",
    "dashboard.last_updated": "છેલ્લું અપડેટ",
    
    // Sensors
    "sensor.temperature": "તાપમાન",
    "sensor.humidity": "ભેજ",
    "sensor.gas": "ગેસ સ્તર",
    "sensor.vibration": "કંપન",
    "sensor.status.safe": "🟢 સુરક્ષિત",
    "sensor.status.warning": "🟡 ચેતવણી",
    "sensor.status.danger": "🔴 જોખમ",
    "sensor.temp.optimal": "શ્રેષ્ઠ શ્રેણી",
    "sensor.temp.high": "થ્રેશોલ્ડ કરતાં વધુ",
    "sensor.humidity.optimal": "શ્રેષ્ઠ શ્રેણી",
    "sensor.humidity.high": "થ્રેશોલ્ડ કરતાં વધુ",
    "sensor.gas.normal": "સામાન્ય સ્તરો",
    "sensor.gas.elevated": "ઊંચા સ્તરો મળ્યા",
    "sensor.vibration.stable": "સ્થિર",
    "sensor.vibration.detected": "પ્રવૃત્તિ મળી",
    
    // Voice Assistant
    "voiceAssistant": "વૉઇસ સહાયક",
    "voiceListening": "સાંભળી રહ્યું છે...",
    "voiceListeningDesc": "બોલવાનું શરૂ કરો",
    "voiceError": "ભૂલ",
    "voiceMicError": "માઇક્રોફોન ઍક્સેસ મેળવી શકાયું નહીં",
    "voiceProcessError": "ઑડિયો પ્રોસેસ કરવામાં ભૂલ",
    "voiceStop": "બંધ કરો",
    "voiceYouSaid": "તમે કહ્યું",
    "voiceAssistantReply": "સહાયકનો જવાબ",
    "voiceAssistantDesc": "માઇક્રોફોન બટન દબાવો અને તમારા અનાજ સંગ્રહ વિશે કંઈક પૂછો",
    
    // Alerts
    "alerts.title": "ચેતવણીઓ",
    "alerts.subtitle": "તાજેતરની સૂચનાઓ અને ચેતવણીઓ",
    "alerts.no_alerts": "હાલમાં કોઈ ચેતવણીઓ નથી",
    "alerts.type.info": "માહિતી",
    "alerts.type.warning": "ચેતવણી",
    "alerts.type.danger": "જોખમ",
    "alerts.type.prediction": "એઆઈ આગાહી",
    
    // Analytics
    "analytics.title": "વિશ્લેષણ",
    "analytics.subtitle": "ઐતિહાસિક ડેટા અને વલણો",
    "analytics.temp_humidity": "તાપમાન અને ભેજ",
    "analytics.temp_humidity.desc": "છેલ્લા 24 કલાક",
    "analytics.gas": "ગેસ સ્તરો",
    "analytics.gas.desc": "પાર્ટ્સ પર મિલિયન (પીપીએમ)",
    "analytics.vibration": "કંપન પ્રવૃત્તિ",
    "analytics.vibration.desc": "હલનચલન શોધ",
    
    // Prediction
    "prediction.title": "એઆઈ-સંચાલિત બગાડ જોખમ વિશ્લેષણ",
    "prediction.subtitle": "અનાજ ગુણવત્તા માટે આગાહી વિશ્લેષણ",
    "prediction.confidence": "વિશ્વાસ",
    "prediction.risk": "જોખમ મૂલ્યાંકન",
    "prediction.risk.low": "ઓછું જોખમ",
    "prediction.risk.medium": "મધ્યમ જોખમ",
    "prediction.risk.high": "ઊંચું જોખમ",
    "prediction.factors": "મુખ્ય યોગદાન આપતા પરિબળો",
    "prediction.actions": "ભલામણ કરેલી ક્રિયાઓ",
    "prediction.action.inspect": "સંગ્રહની તપાસ કરો",
    "prediction.action.ventilate": "વેન્ટિલેશન વધારો",
    "prediction.action.monitor": "નજીકથી નિરીક્ષણ કરો",
    
    // Settings
    "settings.title": "સેટિંગ્સ",
    "settings.subtitle": "થ્રેશોલ્ડ્સ અને સૂચનાઓ ગોઠવો",
    "settings.thresholds": "સુરક્ષા થ્રેશોલ્ડ્સ",
    "settings.temp.max": "મહત્તમ તાપમાન (°C)",
    "settings.temp.min": "લઘુત્તમ તાપમાન (°C)",
    "settings.temp.alert": "જ્યારે તાપમાન આ મૂલ્ય વટાવે ત્યારે ચેતવણી",
    "settings.humidity.max": "મહત્તમ ભેજ (%)",
    "settings.humidity.min": "લઘુત્તમ ભેજ (%)",
    "settings.gas.max": "મહત્તમ ગેસ સ્તર (પીપીએમ)",
    "settings.vibration.max": "મહત્તમ કંપન",
    "settings.notifications": "સૂચનાઓ",
    "settings.notifications.push": "પુશ સૂચનાઓ",
    "settings.notifications.push.desc": "તમારા ઉપકરણ પર ચેતવણીઓ મેળવો",
    "settings.notifications.voice": "વૉઇસ ચેતવણીઓ",
    "settings.notifications.voice.desc": "મહત્વપૂર્ણ ચેતવણીઓ માટે ઑડિઓ સૂચનાઓ સક્ષમ કરો",
    "settings.notifications.sms": "એસએમએસ સૂચનાઓ",
    "settings.notifications.sms.desc": "તાત્કાલિક ચેતવણીઓ માટે ટેક્સ્ટ સંદેશા મોકલો",
    "settings.notifications.ai": "એઆઈ આગાહી ચેતવણીઓ",
    "settings.notifications.ai.desc": "જ્યારે એઆઈ બગાડનું જોખમ શોધે ત્યારે સૂચિત કરો",
    "settings.connection": "કનેક્શન",
    "settings.connection.type": "કનેક્શન પ્રકાર",
    "settings.language": "ભાષા",
    "settings.language.select": "ભાષા પસંદ કરો",
    "settings.save": "સેટિંગ્સ સાચવો",
    "settings.reset": "ડિફૉલ્ટ પર રીસેટ કરો",
    
    // Bluetooth
    "bluetooth.title": "બ્લૂટૂથ સેન્સર",
    "bluetooth.scan": "સેન્સર્સ માટે સ્કેન કરો",
    "bluetooth.disconnect": "ડિસ્કનેક્ટ કરો",
    "bluetooth.status.searching": "સેન્સર્સ શોધી રહ્યા છીએ...",
    "bluetooth.status.connected": "કનેક્ટેડ",
    "bluetooth.status.disconnected": "કનેક્ટેડ નથી",
    "bluetooth.unsupported": "આ બ્રાઉઝરમાં બ્લૂટૂથ સપોર્ટેડ નથી",
  },
  mr: {
    // Navigation
    "nav.dashboard": "डॅशबोर्ड",
    "nav.alerts": "इशारे",
    "nav.analytics": "विश्लेषण",
    "nav.prediction": "एआय अंदाज",
    "nav.settings": "सेटिंग्ज",
    
    // Dashboard
    "dashboard.title": "ग्रेनगार्ड डॅशबोर्ड",
    "dashboard.subtitle": "धान्य साठवण परिस्थितीचे रिअल-टाइम मॉनिटरिंग",
    "dashboard.bluetooth.connected": "ब्लूटूथ कनेक्टेड",
    "dashboard.sensors.title": "सेन्सर रीडिंग्ज",
    "dashboard.status.overview": "स्थिती विहंगावलोकन",
    "dashboard.status.all_systems": "सर्व सिस्टम चालू आहेत",
    "dashboard.status.check_alerts": "तपशीलांसाठी इशारे तपासा",
    "dashboard.last_updated": "शेवटचे अपडेट",
    
    // Sensors
    "sensor.temperature": "तापमान",
    "sensor.humidity": "आर्द्रता",
    "sensor.gas": "गॅस पातळी",
    "sensor.vibration": "कंपन",
    "sensor.status.safe": "🟢 सुरक्षित",
    "sensor.status.warning": "🟡 इशारा",
    "sensor.status.danger": "🔴 धोका",
    "sensor.temp.optimal": "इष्टतम श्रेणी",
    "sensor.temp.high": "मर्यादेपेक्षा जास्त",
    "sensor.humidity.optimal": "इष्टतम श्रेणी",
    "sensor.humidity.high": "मर्यादेपेक्षा जास्त",
    "sensor.gas.normal": "सामान्य पातळी",
    "sensor.gas.elevated": "उच्च पातळी आढळली",
    "sensor.vibration.stable": "स्थिर",
    "sensor.vibration.detected": "क्रियाकलाप आढळले",
    
    // Voice Assistant
    "voiceAssistant": "आवाज सहाय्यक",
    "voiceListening": "ऐकत आहे...",
    "voiceListeningDesc": "बोलणे सुरू करा",
    "voiceError": "त्रुटी",
    "voiceMicError": "मायक्रोफोन प्रवेश मिळू शकला नाही",
    "voiceProcessError": "ऑडिओ प्रक्रिया करताना त्रुटी",
    "voiceStop": "थांबवा",
    "voiceYouSaid": "तुम्ही म्हणालात",
    "voiceAssistantReply": "सहाय्यकाचे उत्तर",
    "voiceAssistantDesc": "मायक्रोफोन बटण दाबा आणि तुमच्या धान्य साठवणुकीबद्दल काहीतरी विचारा",
    
    // Alerts
    "alerts.title": "इशारे",
    "alerts.subtitle": "अलीकडील सूचना आणि इशारे",
    "alerts.no_alerts": "सध्या कोणतेही इशारे नाहीत",
    "alerts.type.info": "माहिती",
    "alerts.type.warning": "इशारा",
    "alerts.type.danger": "धोका",
    "alerts.type.prediction": "एआय अंदाज",
    
    // Analytics
    "analytics.title": "विश्लेषण",
    "analytics.subtitle": "ऐतिहासिक डेटा आणि ट्रेंड",
    "analytics.temp_humidity": "तापमान आणि आर्द्रता",
    "analytics.temp_humidity.desc": "शेवटचे 24 तास",
    "analytics.gas": "गॅस पातळी",
    "analytics.gas.desc": "पार्ट्स प्रति मिलियन (पीपीएम)",
    "analytics.vibration": "कंपन क्रियाकलाप",
    "analytics.vibration.desc": "हालचाल शोध",
    
    // Prediction
    "prediction.title": "एआय-चालित खराब होण्याचा धोका विश्लेषण",
    "prediction.subtitle": "धान्य गुणवत्तेसाठी अंदाज विश्लेषण",
    "prediction.confidence": "विश्वास",
    "prediction.risk": "धोका मूल्यांकन",
    "prediction.risk.low": "कमी धोका",
    "prediction.risk.medium": "मध्यम धोका",
    "prediction.risk.high": "उच्च धोका",
    "prediction.factors": "मुख्य योगदान घटक",
    "prediction.actions": "शिफारस केलेल्या क्रिया",
    "prediction.action.inspect": "साठवण तपासा",
    "prediction.action.ventilate": "वेंटिलेशन वाढवा",
    "prediction.action.monitor": "बारकाईने निरीक्षण करा",
    
    // Settings
    "settings.title": "सेटिंग्ज",
    "settings.subtitle": "मर्यादा आणि सूचना कॉन्फिगर करा",
    "settings.thresholds": "सुरक्षा मर्यादा",
    "settings.temp.max": "कमाल तापमान (°C)",
    "settings.temp.min": "किमान तापमान (°C)",
    "settings.temp.alert": "तापमान या मूल्यापेक्षा जास्त असताना इशारा द्या",
    "settings.humidity.max": "कमाल आर्द्रता (%)",
    "settings.humidity.min": "किमान आर्द्रता (%)",
    "settings.gas.max": "कमाल गॅस पातळी (पीपीएम)",
    "settings.vibration.max": "कमाल कंपन",
    "settings.notifications": "सूचना",
    "settings.notifications.push": "पुश सूचना",
    "settings.notifications.push.desc": "तुमच्या डिव्हाइसवर इशारे मिळवा",
    "settings.notifications.voice": "व्हॉइस इशारे",
    "settings.notifications.voice.desc": "गंभीर इशारे साठी ऑडिओ सूचना सक्षम करा",
    "settings.notifications.sms": "एसएमएस सूचना",
    "settings.notifications.sms.desc": "तातडीच्या इशाऱ्यांसाठी मजकूर संदेश पाठवा",
    "settings.notifications.ai": "एआय अंदाज इशारे",
    "settings.notifications.ai.desc": "एआय खराब होण्याचा धोका शोधते तेव्हा सूचित करा",
    "settings.connection": "कनेक्शन",
    "settings.connection.type": "कनेक्शन प्रकार",
    "settings.language": "भाषा",
    "settings.language.select": "भाषा निवडा",
    "settings.save": "सेटिंग्ज जतन करा",
    "settings.reset": "डीफॉल्टवर रीसेट करा",
    
    // Bluetooth
    "bluetooth.title": "ब्लूटूथ सेन्सर",
    "bluetooth.scan": "सेन्सर्स शोधा",
    "bluetooth.disconnect": "डिस्कनेक्ट करा",
    "bluetooth.status.searching": "सेन्सर्स शोधत आहे...",
    "bluetooth.status.connected": "कनेक्टेड",
    "bluetooth.status.disconnected": "कनेक्टेड नाही",
    "bluetooth.unsupported": "या ब्राउझरमध्ये ब्लूटूथ समर्थित नाही",
  },
  ta: {
    // Navigation
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.alerts": "எச்சரிக்கைகள்",
    "nav.analytics": "பகுப்பாய்வு",
    "nav.prediction": "AI முன்னறிவிப்பு",
    "nav.settings": "அமைப்புகள்",
    
    // Dashboard
    "dashboard.title": "கிரேன்கார்டு டாஷ்போர்டு",
    "dashboard.subtitle": "தானிய சேமிப்பு நிலைமைகளின் நேரடி கண்காணிப்பு",
    "dashboard.bluetooth.connected": "புளூடூத் இணைக்கப்பட்டது",
    "dashboard.sensors.title": "சென்சார் அளவீடுகள்",
    "dashboard.status.overview": "நிலை மேலோட்டம்",
    "dashboard.status.all_systems": "அனைத்து அமைப்புகளும் இயங்குகின்றன",
    "dashboard.status.check_alerts": "விவரங்களுக்கு எச்சரிக்கைகளைச் சரிபார்க்கவும்",
    "dashboard.last_updated": "கடைசியாக புதுப்பிக்கப்பட்டது",
    
    // Sensors
    "sensor.temperature": "வெப்பநிலை",
    "sensor.humidity": "ஈரப்பதம்",
    "sensor.gas": "எரிவாயு அளவு",
    "sensor.vibration": "அதிர்வு",
    "sensor.status.safe": "🟢 பாதுகாப்பானது",
    "sensor.status.warning": "🟡 எச்சரிக்கை",
    "sensor.status.danger": "🔴 ஆபத்து",
    "sensor.temp.optimal": "உகந்த வரம்பு",
    "sensor.temp.high": "வரம்புக்கு மேல்",
    "sensor.humidity.optimal": "உகந்த வரம்பு",
    "sensor.humidity.high": "வரம்புக்கு மேல்",
    "sensor.gas.normal": "சாதாரண நிலைகள்",
    "sensor.gas.elevated": "உயர் நிலைகள் கண்டறியப்பட்டன",
    "sensor.vibration.stable": "நிலையானது",
    "sensor.vibration.detected": "செயல்பாடு கண்டறியப்பட்டது",
    
    // Voice Assistant
    "voiceAssistant": "குரல் உதவியாளர்",
    "voiceListening": "கேட்கிறது...",
    "voiceListeningDesc": "பேசத் தொடங்குங்கள்",
    "voiceError": "பிழை",
    "voiceMicError": "மைக்ரோஃபோன் அணுகல் கிடைக்கவில்லை",
    "voiceProcessError": "ஆடியோ செயலாக்கத்தில் பிழை",
    "voiceStop": "நிறுத்து",
    "voiceYouSaid": "நீங்கள் கூறியது",
    "voiceAssistantReply": "உதவியாளர் பதில்",
    "voiceAssistantDesc": "மைக்ரோஃபோன் பொத்தானை அழுத்தி உங்கள் தானிய சேமிப்பைப் பற்றி கேளுங்கள்",
    
    // Alerts
    "alerts.title": "எச்சரிக்கைகள்",
    "alerts.subtitle": "சமீபத்திய அறிவிப்புகள் மற்றும் எச்சரிக்கைகள்",
    "alerts.no_alerts": "தற்போது எச்சரிக்கைகள் இல்லை",
    "alerts.type.info": "தகவல்",
    "alerts.type.warning": "எச்சரிக்கை",
    "alerts.type.danger": "ஆபத்து",
    "alerts.type.prediction": "AI முன்னறிவிப்பு",
    
    // Analytics
    "analytics.title": "பகுப்பாய்வு",
    "analytics.subtitle": "வரலாற்று தரவு மற்றும் போக்குகள்",
    "analytics.temp_humidity": "வெப்பநிலை மற்றும் ஈரப்பதம்",
    "analytics.temp_humidity.desc": "கடந்த 24 மணி நேரம்",
    "analytics.gas": "எரிவாயு அளவுகள்",
    "analytics.gas.desc": "மில்லியன் ஒன்றுக்கு பாகங்கள் (பிபிஎம்)",
    "analytics.vibration": "அதிர்வு செயல்பாடு",
    "analytics.vibration.desc": "இயக்கம் கண்டறிதல்",
    
    // Prediction
    "prediction.title": "AI-இயக்கப்படும் கெட்டுப்போகும் அபாய பகுப்பாய்வு",
    "prediction.subtitle": "தானிய தரத்திற்கான முன்கணிப்பு பகுப்பாய்வு",
    "prediction.confidence": "நம்பிக்கை",
    "prediction.risk": "அபாய மதிப்பீடு",
    "prediction.risk.low": "குறைந்த அபாயம்",
    "prediction.risk.medium": "மத்திய அபாயம்",
    "prediction.risk.high": "உயர் அபாயம்",
    "prediction.factors": "முக்கிய பங்களிப்பு காரணிகள்",
    "prediction.actions": "பரிந்துரைக்கப்பட்ட செயல்கள்",
    "prediction.action.inspect": "சேமிப்பை ஆய்வு செய்யவும்",
    "prediction.action.ventilate": "காற்றோட்டத்தை அதிகரிக்கவும்",
    "prediction.action.monitor": "நெருக்கமாக கண்காணிக்கவும்",
    
    // Settings
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "வரம்புகள் மற்றும் அறிவிப்புகளை உள்ளமைக்கவும்",
    "settings.thresholds": "பாதுகாப்பு வரம்புகள்",
    "settings.temp.max": "அதிகபட்ச வெப்பநிலை (°C)",
    "settings.temp.min": "குறைந்தபட்ச வெப்பநிலை (°C)",
    "settings.temp.alert": "வெப்பநிலை இந்த மதிப்பை மீறும்போது எச்சரிக்கை",
    "settings.humidity.max": "அதிகபட்ச ஈரப்பதம் (%)",
    "settings.humidity.min": "குறைந்தபட்ச ஈரப்பதம் (%)",
    "settings.gas.max": "அதிகபட்ச எரிவாயு அளவு (பிபிஎம்)",
    "settings.vibration.max": "அதிகபட்ச அதிர்வு",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.notifications.push": "புஷ் அறிவிப்புகள்",
    "settings.notifications.push.desc": "உங்கள் சாதனத்தில் எச்சரிக்கைகளைப் பெறவும்",
    "settings.notifications.voice": "குரல் எச்சரிக்கைகள்",
    "settings.notifications.voice.desc": "முக்கியமான எச்சரிக்கைகளுக்கு ஆடியோ அறிவிப்புகளை இயக்கவும்",
    "settings.notifications.sms": "SMS அறிவிப்புகள்",
    "settings.notifications.sms.desc": "அவசர எச்சரிக்கைகளுக்கு உரைச் செய்திகளை அனுப்பவும்",
    "settings.notifications.ai": "AI முன்னறிவிப்பு எச்சரிக்கைகள்",
    "settings.notifications.ai.desc": "AI கெட்டுப்போகும் அபாயத்தைக் கண்டறியும் போது அறிவிக்கவும்",
    "settings.connection": "இணைப்பு",
    "settings.connection.type": "இணைப்பு வகை",
    "settings.language": "மொழி",
    "settings.language.select": "மொழியைத் தேர்ந்தெடுக்கவும்",
    "settings.save": "அமைப்புகளைச் சேமிக்கவும்",
    "settings.reset": "இயல்புநிலைக்கு மீட்டமைக்கவும்",
    
    // Bluetooth
    "bluetooth.title": "புளூடூத் சென்சார்",
    "bluetooth.scan": "சென்சார்களை ஸ்கேன் செய்யவும்",
    "bluetooth.disconnect": "துண்டிக்கவும்",
    "bluetooth.status.searching": "சென்சார்களைத் தேடுகிறது...",
    "bluetooth.status.connected": "இணைக்கப்பட்டது",
    "bluetooth.status.disconnected": "இணைக்கப்படவில்லை",
    "bluetooth.unsupported": "இந்த உலாவியில் புளூடூத் ஆதரிக்கப்படவில்லை",
  },
  te: {
    // Navigation
    "nav.dashboard": "డాష్‌బోర్డ్",
    "nav.alerts": "హెచ్చరికలు",
    "nav.analytics": "విశ్లేషణ",
    "nav.prediction": "AI అంచనా",
    "nav.settings": "సెట్టింగ్‌లు",
    
    // Dashboard
    "dashboard.title": "గ్రేన్‌గార్డ్ డాష్‌బోర్డ్",
    "dashboard.subtitle": "ధాన్య నిల్వ పరిస్థితుల రియల్-టైమ్ పర్యవేక్షణ",
    "dashboard.bluetooth.connected": "బ్లూటూత్ కనెక్ట్ అయింది",
    "dashboard.sensors.title": "సెన్సార్ రీడింగ్‌లు",
    "dashboard.status.overview": "స్థితి అవలోకనం",
    "dashboard.status.all_systems": "అన్ని వ్యవస్థలు పనిచేస్తున్నాయి",
    "dashboard.status.check_alerts": "వివరాల కోసం హెచ్చరికలను తనిఖీ చేయండి",
    "dashboard.last_updated": "చివరిగా నవీకరించబడింది",
    
    // Sensors
    "sensor.temperature": "ఉష్ణోగ్రత",
    "sensor.humidity": "తేమ",
    "sensor.gas": "గ్యాస్ స్థాయి",
    "sensor.vibration": "కంపనం",
    "sensor.status.safe": "🟢 సురక్షితం",
    "sensor.status.warning": "🟡 హెచ్చరిక",
    "sensor.status.danger": "🔴 ప్రమాదం",
    "sensor.temp.optimal": "సరైన పరిధి",
    "sensor.temp.high": "థ్రెషోల్డ్ కంటే ఎక్కువ",
    "sensor.humidity.optimal": "సరైన పరిధి",
    "sensor.humidity.high": "థ్రెషోల్డ్ కంటే ఎక్కువ",
    "sensor.gas.normal": "సాధారణ స్థాయిలు",
    "sensor.gas.elevated": "అధిక స్థాయిలు గుర్తించబడ్డాయి",
    "sensor.vibration.stable": "స్థిరమైనది",
    "sensor.vibration.detected": "కార్యాచరణ గుర్తించబడింది",
    
    // Voice Assistant
    "voiceAssistant": "వాయిస్ అసిస్టెంట్",
    "voiceListening": "వింటోంది...",
    "voiceListeningDesc": "మాట్లాడటం ప్రారంభించండి",
    "voiceError": "లోపం",
    "voiceMicError": "మైక్రోఫోన్ యాక్సెస్ పొందలేకపోయింది",
    "voiceProcessError": "ఆడియో ప్రాసెసింగ్‌లో లోపం",
    "voiceStop": "ఆపు",
    "voiceYouSaid": "మీరు చెప్పారు",
    "voiceAssistantReply": "అసిస్టెంట్ సమాధానం",
    "voiceAssistantDesc": "మైక్రోఫోన్ బటన్ నొక్కి మీ ధాన్యం నిల్వ గురించి ఏదైనా అడగండి",
    
    // Alerts
    "alerts.title": "హెచ్చరికలు",
    "alerts.subtitle": "ఇటీవలి నోటిఫికేషన్‌లు మరియు హెచ్చరికలు",
    "alerts.no_alerts": "ప్రస్తుతం హెచ్చరికలు లేవు",
    "alerts.type.info": "సమాచారం",
    "alerts.type.warning": "హెచ్చరిక",
    "alerts.type.danger": "ప్రమాదం",
    "alerts.type.prediction": "AI అంచనా",
    
    // Analytics
    "analytics.title": "విశ్లేషణ",
    "analytics.subtitle": "చారిత్రక డేటా మరియు ధోరణులు",
    "analytics.temp_humidity": "ఉష్ణోగ్రత మరియు తేమ",
    "analytics.temp_humidity.desc": "గత 24 గంటలు",
    "analytics.gas": "గ్యాస్ స్థాయిలు",
    "analytics.gas.desc": "మిలియన్‌కు భాగాలు (పిపిఎం)",
    "analytics.vibration": "కంపన కార్యాచరణ",
    "analytics.vibration.desc": "కదలిక గుర్తింపు",
    
    // Prediction
    "prediction.title": "AI-ఆధారిత చెడిపోయే ప్రమాద విశ్లేషణ",
    "prediction.subtitle": "ధాన్య నాణ్యత కోసం అంచనా విశ్లేషణ",
    "prediction.confidence": "విశ్వాసం",
    "prediction.risk": "ప్రమాద అంచనా",
    "prediction.risk.low": "తక్కువ ప్రమాదం",
    "prediction.risk.medium": "మధ్యస్థ ప్రమాదం",
    "prediction.risk.high": "అధిక ప్రమాదం",
    "prediction.factors": "ముఖ్య సహకార కారకాలు",
    "prediction.actions": "సిఫార్సు చేయబడిన చర్యలు",
    "prediction.action.inspect": "నిల్వను తనిఖీ చేయండి",
    "prediction.action.ventilate": "వెంటిలేషన్ పెంచండి",
    "prediction.action.monitor": "దగ్గరగా పర్యవేక్షించండి",
    
    // Settings
    "settings.title": "సెట్టింగ్‌లు",
    "settings.subtitle": "థ్రెషోల్డ్‌లు మరియు నోటిఫికేషన్‌లను కాన్ఫిగర్ చేయండి",
    "settings.thresholds": "భద్రతా థ్రెషోల్డ్‌లు",
    "settings.temp.max": "గరిష్ట ఉష్ణోగ్రత (°C)",
    "settings.temp.min": "కనిష్ట ఉష్ణోగ్రత (°C)",
    "settings.temp.alert": "ఉష్ణోగ్రత ఈ విలువను మించినప్పుడు హెచ్చరిక",
    "settings.humidity.max": "గరిష్ట తేమ (%)",
    "settings.humidity.min": "కనిష్ట తేమ (%)",
    "settings.gas.max": "గరిష్ట గ్యాస్ స్థాయి (పిపిఎం)",
    "settings.vibration.max": "గరిష్ట కంపనం",
    "settings.notifications": "నోటిఫికేషన్‌లు",
    "settings.notifications.push": "పుష్ నోటిఫికేషన్‌లు",
    "settings.notifications.push.desc": "మీ పరికరంలో హెచ్చరికలను స్వీకరించండి",
    "settings.notifications.voice": "వాయిస్ హెచ్చరికలు",
    "settings.notifications.voice.desc": "క్లిష్ట హెచ్చరికల కోసం ఆడియో నోటిఫికేషన్‌లను ప్రారంభించండి",
    "settings.notifications.sms": "SMS నోటిఫికేషన్‌లు",
    "settings.notifications.sms.desc": "అత్యవసర హెచ్చరికల కోసం టెక్స్ట్ సందేశాలు పంపండి",
    "settings.notifications.ai": "AI అంచనా హెచ్చరికలు",
    "settings.notifications.ai.desc": "AI చెడిపోయే ప్రమాదాన్ని గుర్తించినప్పుడు తెలియజేయండి",
    "settings.connection": "కనెక్షన్",
    "settings.connection.type": "కనెక్షన్ రకం",
    "settings.language": "భాష",
    "settings.language.select": "భాషను ఎంచుకోండి",
    "settings.save": "సెట్టింగ్‌లను సేవ్ చేయండి",
    "settings.reset": "డిఫాల్ట్‌కు రీసెట్ చేయండి",
    
    // Bluetooth
    "bluetooth.title": "బ్లూటూత్ సెన్సార్",
    "bluetooth.scan": "సెన్సార్‌ల కోసం స్కాన్ చేయండి",
    "bluetooth.disconnect": "డిస్‌కనెక్ట్ చేయండి",
    "bluetooth.status.searching": "సెన్సార్‌ల కోసం వెతుకుతోంది...",
    "bluetooth.status.connected": "కనెక్ట్ అయింది",
    "bluetooth.status.disconnected": "కనెక్ట్ కాలేదు",
    "bluetooth.unsupported": "ఈ బ్రౌజర్‌లో బ్లూటూత్ మద్దతు లేదు",
  },
  ml: {
    // Navigation
    "nav.dashboard": "ഡാഷ്‌ബോർഡ്",
    "nav.alerts": "മുന്നറിയിപ്പുകൾ",
    "nav.analytics": "വിശകലനം",
    "nav.prediction": "AI പ്രവചനം",
    "nav.settings": "ക്രമീകരണങ്ങൾ",
    
    // Dashboard
    "dashboard.title": "ഗ്രെയിൻഗാർഡ് ഡാഷ്‌ബോർഡ്",
    "dashboard.subtitle": "ധാന്യ സംഭരണ ​​അവസ്ഥകളുടെ തത്സമയ നിരീക്ഷണം",
    "dashboard.bluetooth.connected": "ബ്ലൂടൂത്ത് കണക്റ്റുചെയ്‌തു",
    "dashboard.sensors.title": "സെൻസർ റീഡിംഗുകൾ",
    "dashboard.status.overview": "സ്ഥിതി അവലോകനം",
    "dashboard.status.all_systems": "എല്ലാ സംവിധാനങ്ങളും പ്രവർത്തിക്കുന്നു",
    "dashboard.status.check_alerts": "വിശദാംശങ്ങൾക്കായി മുന്നറിയിപ്പുകൾ പരിശോധിക്കുക",
    "dashboard.last_updated": "അവസാനം അപ്‌ഡേറ്റ് ചെയ്‌തത്",
    
    // Sensors
    "sensor.temperature": "താപനില",
    "sensor.humidity": "ഈർപ്പം",
    "sensor.gas": "വാതക നില",
    "sensor.vibration": "വൈബ്രേഷൻ",
    "sensor.status.safe": "🟢 സുരക്ഷിതം",
    "sensor.status.warning": "🟡 മുന്നറിയിപ്പ്",
    "sensor.status.danger": "🔴 അപകടം",
    "sensor.temp.optimal": "ഒപ്റ്റിമൽ ശ്രേണി",
    "sensor.temp.high": "പരിധിക്ക് മുകളിൽ",
    "sensor.humidity.optimal": "ഒപ്റ്റിമൽ ശ്രേണി",
    "sensor.humidity.high": "പരിധിക്ക് മുകളിൽ",
    "sensor.gas.normal": "സാധാരണ നിലകൾ",
    "sensor.gas.elevated": "ഉയർന്ന നിലകൾ കണ്ടെത്തി",
    "sensor.vibration.stable": "സ്ഥിരതയുള്ളത്",
    "sensor.vibration.detected": "പ്രവർത്തനം കണ്ടെത്തി",
    
    // Alerts
    "alerts.title": "മുന്നറിയിപ്പുകൾ",
    "alerts.subtitle": "സമീപകാല അറിയിപ്പുകളും മുന്നറിയിപ്പുകളും",
    "alerts.no_alerts": "നിലവിൽ മുന്നറിയിപ്പുകളൊന്നുമില്ല",
    "alerts.type.info": "വിവരം",
    "alerts.type.warning": "മുന്നറിയിപ്പ്",
    "alerts.type.danger": "അപകടം",
    "alerts.type.prediction": "AI പ്രവചനം",
    
    // Analytics
    "analytics.title": "വിശകലനം",
    "analytics.subtitle": "ചരിത്ര ഡാറ്റയും പ്രവണതകളും",
    "analytics.temp_humidity": "താപനിലയും ഈർപ്പവും",
    "analytics.temp_humidity.desc": "കഴിഞ്ഞ 24 മണിക്കൂർ",
    "analytics.gas": "വാതക നിലകൾ",
    "analytics.gas.desc": "മില്യണിന് ഭാഗങ്ങൾ (പിപിഎം)",
    "analytics.vibration": "വൈബ്രേഷൻ പ്രവർത്തനം",
    "analytics.vibration.desc": "ചലന കണ്ടെത്തൽ",
    
    // Prediction
    "prediction.title": "AI-നയിക്കുന്ന കേടാകൽ അപകട വിശകലനം",
    "prediction.subtitle": "ധാന്യ ഗുണനിലവാരത്തിനുള്ള പ്രവചന വിശകലനം",
    "prediction.confidence": "വിശ്വാസം",
    "prediction.risk": "അപകട വിലയിരുത്തൽ",
    "prediction.risk.low": "കുറഞ്ഞ അപകടം",
    "prediction.risk.medium": "ഇടത്തരം അപകടം",
    "prediction.risk.high": "ഉയർന്ന അപകടം",
    "prediction.factors": "പ്രധാന സംഭാവന ഘടകങ്ങൾ",
    "prediction.actions": "ശുപാർശ ചെയ്യുന്ന പ്രവർത്തനങ്ങൾ",
    "prediction.action.inspect": "സംഭരണം പരിശോധിക്കുക",
    "prediction.action.ventilate": "വെന്റിലേഷൻ വർദ്ധിപ്പിക്കുക",
    "prediction.action.monitor": "അടുത്ത് നിരീക്ഷിക്കുക",
    
    // Settings
    "settings.title": "ക്രമീകരണങ്ങൾ",
    "settings.subtitle": "പരിധികളും അറിയിപ്പുകളും കോൺഫിഗർ ചെയ്യുക",
    "settings.thresholds": "സുരക്ഷാ പരിധികൾ",
    "settings.temp.max": "പരമാവധി താപനില (°C)",
    "settings.temp.min": "മിനിമം താപനില (°C)",
    "settings.temp.alert": "താപനില ഈ മൂല്യം കവിയുമ്പോൾ മുന്നറിയിപ്പ്",
    "settings.humidity.max": "പരമാവധി ഈർപ്പം (%)",
    "settings.humidity.min": "മിനിമം ഈർപ്പം (%)",
    "settings.gas.max": "പരമാവധി വാതക നില (പിപിഎം)",
    "settings.vibration.max": "പരമാവധി വൈബ്രേഷൻ",
    "settings.notifications": "അറിയിപ്പുകൾ",
    "settings.notifications.push": "പുഷ് അറിയിപ്പുകൾ",
    "settings.notifications.push.desc": "നിങ്ങളുടെ ഉപകരണത്തിൽ മുന്നറിയിപ്പുകൾ സ്വീകരിക്കുക",
    "settings.notifications.voice": "ശബ്ദ മുന്നറിയിപ്പുകൾ",
    "settings.notifications.voice.desc": "നിർണായക മുന്നറിയിപ്പുകൾക്കായി ഓഡിയോ അറിയിപ്പുകൾ പ്രവർത്തനക്ഷമമാക്കുക",
    "settings.notifications.sms": "SMS അറിയിപ്പുകൾ",
    "settings.notifications.sms.desc": "അടിയന്തര മുന്നറിയിപ്പുകൾക്കായി ടെക്‌സ്റ്റ് സന്ദേശങ്ങൾ അയയ്‌ക്കുക",
    "settings.notifications.ai": "AI പ്രവചന മുന്നറിയിപ്പുകൾ",
    "settings.notifications.ai.desc": "AI കേടാകൽ അപകടം കണ്ടെത്തുമ്പോൾ അറിയിക്കുക",
    "settings.connection": "കണക്ഷൻ",
    "settings.connection.type": "കണക്ഷൻ തരം",
    "settings.language": "ഭാഷ",
    "settings.language.select": "ഭാഷ തിരഞ്ഞെടുക്കുക",
    "settings.save": "ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുക",
    "settings.reset": "ഡിഫോൾട്ടിലേക്ക് പുനഃസജ്ജമാക്കുക",
    
    // Bluetooth
    "bluetooth.title": "ബ്ലൂടൂത്ത് സെൻസർ",
    "bluetooth.scan": "സെൻസറുകൾക്കായി സ്‌കാൻ ചെയ്യുക",
    "bluetooth.disconnect": "വിച്ഛേദിക്കുക",
    "bluetooth.status.searching": "സെൻസറുകൾ തിരയുന്നു...",
    "bluetooth.status.connected": "കണക്റ്റുചെയ്‌തു",
    "bluetooth.status.disconnected": "കണക്റ്റുചെയ്‌തിട്ടില്ല",
    "bluetooth.unsupported": "ഈ ബ്രൗസറിൽ ബ്ലൂടൂത്ത് പിന്തുണയ്‌ക്കുന്നില്ല",
  },
  pa: {
    // Navigation
    "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "nav.alerts": "ਚੇਤਾਵਨੀਆਂ",
    "nav.analytics": "ਵਿਸ਼ਲੇਸ਼ਣ",
    "nav.prediction": "AI ਪੂਰਵ ਅਨੁਮਾਨ",
    "nav.settings": "ਸੈਟਿੰਗਾਂ",
    
    // Dashboard
    "dashboard.title": "ਗ੍ਰੇਨਗਾਰਡ ਡੈਸ਼ਬੋਰਡ",
    "dashboard.subtitle": "ਅਨਾਜ ਸਟੋਰੇਜ ਸਥਿਤੀਆਂ ਦੀ ਰੀਅਲ-ਟਾਈਮ ਨਿਗਰਾਨੀ",
    "dashboard.bluetooth.connected": "ਬਲੂਟੁੱਥ ਕਨੈਕਟ ਹੋਇਆ",
    "dashboard.sensors.title": "ਸੈਂਸਰ ਰੀਡਿੰਗਾਂ",
    "dashboard.status.overview": "ਸਥਿਤੀ ਸੰਖੇਪ",
    "dashboard.status.all_systems": "ਸਾਰੀਆਂ ਪ੍ਰਣਾਲੀਆਂ ਕੰਮ ਕਰ ਰਹੀਆਂ ਹਨ",
    "dashboard.status.check_alerts": "ਵੇਰਵਿਆਂ ਲਈ ਚੇਤਾਵਨੀਆਂ ਦੀ ਜਾਂਚ ਕਰੋ",
    "dashboard.last_updated": "ਆਖਰੀ ਅੱਪਡੇਟ",
    
    // Sensors
    "sensor.temperature": "ਤਾਪਮਾਨ",
    "sensor.humidity": "ਨਮੀ",
    "sensor.gas": "ਗੈਸ ਪੱਧਰ",
    "sensor.vibration": "ਕੰਬਣੀ",
    "sensor.status.safe": "🟢 ਸੁਰੱਖਿਅਤ",
    "sensor.status.warning": "🟡 ਚੇਤਾਵਨੀ",
    "sensor.status.danger": "🔴 ਖਤਰਾ",
    "sensor.temp.optimal": "ਅਨੁਕੂਲ ਸੀਮਾ",
    "sensor.temp.high": "ਥ੍ਰੈਸ਼ਹੋਲਡ ਤੋਂ ਉੱਪਰ",
    "sensor.humidity.optimal": "ਅਨੁਕੂਲ ਸੀਮਾ",
    "sensor.humidity.high": "ਥ੍ਰੈਸ਼ਹੋਲਡ ਤੋਂ ਉੱਪਰ",
    "sensor.gas.normal": "ਸਧਾਰਨ ਪੱਧਰ",
    "sensor.gas.elevated": "ਉੱਚੇ ਪੱਧਰ ਪਾਏ ਗਏ",
    "sensor.vibration.stable": "ਸਥਿਰ",
    "sensor.vibration.detected": "ਗਤੀਵਿਧੀ ਪਾਈ ਗਈ",
    
    // Alerts
    "alerts.title": "ਚੇਤਾਵਨੀਆਂ",
    "alerts.subtitle": "ਤਾਜ਼ਾ ਸੂਚਨਾਵਾਂ ਅਤੇ ਚੇਤਾਵਨੀਆਂ",
    "alerts.no_alerts": "ਇਸ ਸਮੇਂ ਕੋਈ ਚੇਤਾਵਨੀਆਂ ਨਹੀਂ",
    "alerts.type.info": "ਜਾਣਕਾਰੀ",
    "alerts.type.warning": "ਚੇਤਾਵਨੀ",
    "alerts.type.danger": "ਖਤਰਾ",
    "alerts.type.prediction": "AI ਪੂਰਵ ਅਨੁਮਾਨ",
    
    // Analytics
    "analytics.title": "ਵਿਸ਼ਲੇਸ਼ਣ",
    "analytics.subtitle": "ਇਤਿਹਾਸਕ ਡੇਟਾ ਅਤੇ ਰੁਝਾਨ",
    "analytics.temp_humidity": "ਤਾਪਮਾਨ ਅਤੇ ਨਮੀ",
    "analytics.temp_humidity.desc": "ਪਿਛਲੇ 24 ਘੰਟੇ",
    "analytics.gas": "ਗੈਸ ਪੱਧਰ",
    "analytics.gas.desc": "ਪਾਰਟਸ ਪ੍ਰਤੀ ਮਿਲੀਅਨ (ਪੀਪੀਐਮ)",
    "analytics.vibration": "ਕੰਬਣੀ ਗਤੀਵਿਧੀ",
    "analytics.vibration.desc": "ਗਤੀ ਦੀ ਖੋਜ",
    
    // Prediction
    "prediction.title": "AI-ਸੰਚਾਲਿਤ ਖਰਾਬੀ ਜੋਖਮ ਵਿਸ਼ਲੇਸ਼ਣ",
    "prediction.subtitle": "ਅਨਾਜ ਗੁਣਵੱਤਾ ਲਈ ਪੂਰਵ ਅਨੁਮਾਨ ਵਿਸ਼ਲੇਸ਼ਣ",
    "prediction.confidence": "ਵਿਸ਼ਵਾਸ",
    "prediction.risk": "ਜੋਖਮ ਮੁਲਾਂਕਣ",
    "prediction.risk.low": "ਘੱਟ ਜੋਖਮ",
    "prediction.risk.medium": "ਮੱਧਮ ਜੋਖਮ",
    "prediction.risk.high": "ਉੱਚ ਜੋਖਮ",
    "prediction.factors": "ਮੁੱਖ ਯੋਗਦਾਨ ਕਾਰਕ",
    "prediction.actions": "ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਕਾਰਵਾਈਆਂ",
    "prediction.action.inspect": "ਸਟੋਰੇਜ ਦੀ ਜਾਂਚ ਕਰੋ",
    "prediction.action.ventilate": "ਹਵਾਦਾਰੀ ਵਧਾਓ",
    "prediction.action.monitor": "ਨੇੜਿਓਂ ਨਿਗਰਾਨੀ ਕਰੋ",
    
    // Settings
    "settings.title": "ਸੈਟਿੰਗਾਂ",
    "settings.subtitle": "ਥ੍ਰੈਸ਼ਹੋਲਡ ਅਤੇ ਸੂਚਨਾਵਾਂ ਸੰਰਚਿਤ ਕਰੋ",
    "settings.thresholds": "ਸੁਰੱਖਿਆ ਥ੍ਰੈਸ਼ਹੋਲਡ",
    "settings.temp.max": "ਵੱਧ ਤੋਂ ਵੱਧ ਤਾਪਮਾਨ (°C)",
    "settings.temp.min": "ਘੱਟੋ-ਘੱਟ ਤਾਪਮਾਨ (°C)",
    "settings.temp.alert": "ਜਦੋਂ ਤਾਪਮਾਨ ਇਸ ਮੁੱਲ ਤੋਂ ਵੱਧ ਜਾਵੇ ਤਾਂ ਚੇਤਾਵਨੀ",
    "settings.humidity.max": "ਵੱਧ ਤੋਂ ਵੱਧ ਨਮੀ (%)",
    "settings.humidity.min": "ਘੱਟੋ-ਘੱਟ ਨਮੀ (%)",
    "settings.gas.max": "ਵੱਧ ਤੋਂ ਵੱਧ ਗੈਸ ਪੱਧਰ (ਪੀਪੀਐਮ)",
    "settings.vibration.max": "ਵੱਧ ਤੋਂ ਵੱਧ ਕੰਬਣੀ",
    "settings.notifications": "ਸੂਚਨਾਵਾਂ",
    "settings.notifications.push": "ਪੁਸ਼ ਸੂਚਨਾਵਾਂ",
    "settings.notifications.push.desc": "ਆਪਣੇ ਡਿਵਾਈਸ 'ਤੇ ਚੇਤਾਵਨੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    "settings.notifications.voice": "ਵੌਇਸ ਚੇਤਾਵਨੀਆਂ",
    "settings.notifications.voice.desc": "ਮਹੱਤਵਪੂਰਨ ਚੇਤਾਵਨੀਆਂ ਲਈ ਔਡੀਓ ਸੂਚਨਾਵਾਂ ਸਮਰੱਥ ਕਰੋ",
    "settings.notifications.sms": "SMS ਸੂਚਨਾਵਾਂ",
    "settings.notifications.sms.desc": "ਜ਼ਰੂਰੀ ਚੇਤਾਵਨੀਆਂ ਲਈ ਟੈਕਸਟ ਸੁਨੇਹੇ ਭੇਜੋ",
    "settings.notifications.ai": "AI ਪੂਰਵ ਅਨੁਮਾਨ ਚੇਤਾਵਨੀਆਂ",
    "settings.notifications.ai.desc": "ਜਦੋਂ AI ਖਰਾਬੀ ਦਾ ਜੋਖਮ ਖੋਜਦਾ ਹੈ ਤਾਂ ਸੂਚਿਤ ਕਰੋ",
    "settings.connection": "ਕਨੈਕਸ਼ਨ",
    "settings.connection.type": "ਕਨੈਕਸ਼ਨ ਕਿਸਮ",
    "settings.language": "ਭਾਸ਼ਾ",
    "settings.language.select": "ਭਾਸ਼ਾ ਚੁਣੋ",
    "settings.save": "ਸੈਟਿੰਗਾਂ ਸੰਭਾਲੋ",
    "settings.reset": "ਡਿਫੌਲਟ 'ਤੇ ਰੀਸੈੱਟ ਕਰੋ",
    
    // Bluetooth
    "bluetooth.title": "ਬਲੂਟੁੱਥ ਸੈਂਸਰ",
    "bluetooth.scan": "ਸੈਂਸਰਾਂ ਲਈ ਸਕੈਨ ਕਰੋ",
    "bluetooth.disconnect": "ਡਿਸਕਨੈਕਟ ਕਰੋ",
    "bluetooth.status.searching": "ਸੈਂਸਰਾਂ ਦੀ ਖੋਜ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    "bluetooth.status.connected": "ਕਨੈਕਟ ਹੋਇਆ",
    "bluetooth.status.disconnected": "ਕਨੈਕਟ ਨਹੀਂ",
    "bluetooth.unsupported": "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਬਲੂਟੁੱਥ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ",
  },
  ur: {
    // Navigation
    "nav.dashboard": "ڈیش بورڈ",
    "nav.alerts": "الرٹس",
    "nav.analytics": "تجزیات",
    "nav.prediction": "AI پیشن گوئی",
    "nav.settings": "ترتیبات",
    
    // Dashboard
    "dashboard.title": "گرین گارڈ ڈیش بورڈ",
    "dashboard.subtitle": "اناج ذخیرہ کرنے کے حالات کی حقیقی وقت نگرانی",
    "dashboard.bluetooth.connected": "بلوٹوتھ منسلک ہے",
    "dashboard.sensors.title": "سینسر ریڈنگز",
    "dashboard.status.overview": "صورتحال کا جائزہ",
    "dashboard.status.all_systems": "تمام نظام چل رہے ہیں",
    "dashboard.status.check_alerts": "تفصیلات کے لیے الرٹس چیک کریں",
    "dashboard.last_updated": "آخری اپ ڈیٹ",
    
    // Sensors
    "sensor.temperature": "درجہ حرارت",
    "sensor.humidity": "نمی",
    "sensor.gas": "گیس کی سطح",
    "sensor.vibration": "کمپن",
    "sensor.status.safe": "🟢 محفوظ",
    "sensor.status.warning": "🟡 انتباہ",
    "sensor.status.danger": "🔴 خطرہ",
    "sensor.temp.optimal": "بہترین حد",
    "sensor.temp.high": "حد سے اوپر",
    "sensor.humidity.optimal": "بہترین حد",
    "sensor.humidity.high": "حد سے اوپر",
    "sensor.gas.normal": "عام سطحیں",
    "sensor.gas.elevated": "بلند سطحیں پائی گئیں",
    "sensor.vibration.stable": "مستحکم",
    "sensor.vibration.detected": "سرگرمی پائی گئی",
    
    // Alerts
    "alerts.title": "الرٹس",
    "alerts.subtitle": "حالیہ اطلاعات اور انتباہات",
    "alerts.no_alerts": "فی الوقت کوئی الرٹس نہیں",
    "alerts.type.info": "معلومات",
    "alerts.type.warning": "انتباہ",
    "alerts.type.danger": "خطرہ",
    "alerts.type.prediction": "AI پیشن گوئی",
    
    // Analytics
    "analytics.title": "تجزیات",
    "analytics.subtitle": "تاریخی ڈیٹا اور رجحانات",
    "analytics.temp_humidity": "درجہ حرارت اور نمی",
    "analytics.temp_humidity.desc": "آخری 24 گھنٹے",
    "analytics.gas": "گیس کی سطحیں",
    "analytics.gas.desc": "فی ملین حصے (پی پی ایم)",
    "analytics.vibration": "کمپن کی سرگرمی",
    "analytics.vibration.desc": "حرکت کا پتہ لگانا",
    
    // Prediction
    "prediction.title": "AI سے چلنے والا خراب ہونے کے خطرے کا تجزیہ",
    "prediction.subtitle": "اناج کے معیار کے لیے پیشن گوئی تجزیہ",
    "prediction.confidence": "اعتماد",
    "prediction.risk": "خطرے کی تشخیص",
    "prediction.risk.low": "کم خطرہ",
    "prediction.risk.medium": "درمیانی خطرہ",
    "prediction.risk.high": "زیادہ خطرہ",
    "prediction.factors": "اہم شراکت کرنے والے عوامل",
    "prediction.actions": "تجویز کردہ اقدامات",
    "prediction.action.inspect": "ذخیرہ کی جانچ کریں",
    "prediction.action.ventilate": "ہوا کا بہاؤ بڑھائیں",
    "prediction.action.monitor": "قریب سے نگرانی کریں",
    
    // Settings
    "settings.title": "ترتیبات",
    "settings.subtitle": "حدیں اور اطلاعات ترتیب دیں",
    "settings.thresholds": "حفاظتی حدیں",
    "settings.temp.max": "زیادہ سے زیادہ درجہ حرارت (°C)",
    "settings.temp.min": "کم سے کم درجہ حرارت (°C)",
    "settings.temp.alert": "جب درجہ حرارت اس قیمت سے زیادہ ہو تو الرٹ کریں",
    "settings.humidity.max": "زیادہ سے زیادہ نمی (%)",
    "settings.humidity.min": "کم سے کم نمی (%)",
    "settings.gas.max": "زیادہ سے زیادہ گیس کی سطح (پی پی ایم)",
    "settings.vibration.max": "زیادہ سے زیادہ کمپن",
    "settings.notifications": "اطلاعات",
    "settings.notifications.push": "پش اطلاعات",
    "settings.notifications.push.desc": "اپنے ڈیوائس پر الرٹس وصول کریں",
    "settings.notifications.voice": "صوتی الرٹس",
    "settings.notifications.voice.desc": "اہم الرٹس کے لیے آڈیو اطلاعات فعال کریں",
    "settings.notifications.sms": "SMS اطلاعات",
    "settings.notifications.sms.desc": "فوری الرٹس کے لیے ٹیکسٹ پیغامات بھیجیں",
    "settings.notifications.ai": "AI پیشن گوئی الرٹس",
    "settings.notifications.ai.desc": "جب AI خراب ہونے کا خطرہ معلوم کرے تو مطلع کریں",
    "settings.connection": "کنکشن",
    "settings.connection.type": "کنکشن کی قسم",
    "settings.language": "زبان",
    "settings.language.select": "زبان منتخب کریں",
    "settings.save": "ترتیبات محفوظ کریں",
    "settings.reset": "ڈیفالٹ پر دوبارہ ترتیب دیں",
    
    // Bluetooth
    "bluetooth.title": "بلوٹوتھ سینسر",
    "bluetooth.scan": "سینسرز کے لیے اسکین کریں",
    "bluetooth.disconnect": "منقطع کریں",
    "bluetooth.status.searching": "سینسرز تلاش کر رہے ہیں...",
    "bluetooth.status.connected": "منسلک ہے",
    "bluetooth.status.disconnected": "منسلک نہیں",
    "bluetooth.unsupported": "اس براؤزر میں بلوٹوتھ تعاون یافتہ نہیں ہے",
  },
  kn: {
    // Navigation
    "nav.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "nav.alerts": "ಎಚ್ಚರಿಕೆಗಳು",
    "nav.analytics": "ವಿಶ್ಲೇಷಣೆ",
    "nav.prediction": "AI ಮುನ್ಸೂಚನೆ",
    "nav.settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    
    // Dashboard
    "dashboard.title": "ಗ್ರೇನ್‌ಗಾರ್ಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "dashboard.subtitle": "ಧಾನ್ಯ ಸಂಗ್ರಹಣೆ ಪರಿಸ್ಥಿತಿಗಳ ನೈಜ ಸಮಯದ ಮೇಲ್ವಿಚಾರಣೆ",
    "dashboard.bluetooth.connected": "ಬ್ಲೂಟೂತ್ ಸಂಪರ್ಕಗೊಂಡಿದೆ",
    "dashboard.sensors.title": "ಸಂವೇದಕ ರೀಡಿಂಗ್‌ಗಳು",
    "dashboard.status.overview": "ಸ್ಥಿತಿ ಅವಲೋಕನ",
    "dashboard.status.all_systems": "ಎಲ್ಲಾ ವ್ಯವಸ್ಥೆಗಳು ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿವೆ",
    "dashboard.status.check_alerts": "ವಿವರಗಳಿಗಾಗಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    "dashboard.last_updated": "ಕೊನೆಯ ನವೀಕರಣ",
    
    // Sensors
    "sensor.temperature": "ತಾಪಮಾನ",
    "sensor.humidity": "ತೇವಾಂಶ",
    "sensor.gas": "ಅನಿಲ ಮಟ್ಟ",
    "sensor.vibration": "ಕಂಪನ",
    "sensor.status.safe": "🟢 ಸುರಕ್ಷಿತ",
    "sensor.status.warning": "🟡 ಎಚ್ಚರಿಕೆ",
    "sensor.status.danger": "🔴 ಅಪಾಯ",
    "sensor.temp.optimal": "ಅತ್ಯುತ್ತಮ ವ್ಯಾಪ್ತಿ",
    "sensor.temp.high": "ಮಿತಿಗಿಂತ ಹೆಚ್ಚು",
    "sensor.humidity.optimal": "ಅತ್ಯುತ್ತಮ ವ್ಯಾಪ್ತಿ",
    "sensor.humidity.high": "ಮಿತಿಗಿಂತ ಹೆಚ್ಚು",
    "sensor.gas.normal": "ಸಾಮಾನ್ಯ ಮಟ್ಟಗಳು",
    "sensor.gas.elevated": "ಹೆಚ್ಚಿನ ಮಟ್ಟಗಳು ಕಂಡುಬಂದಿವೆ",
    "sensor.vibration.stable": "ಸ್ಥಿರ",
    "sensor.vibration.detected": "ಚಟುವಟಿಕೆ ಪತ್ತೆಯಾಗಿದೆ",
    
    // Voice Assistant
    "voiceAssistant": "ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್",
    "voiceListening": "ಕೇಳುತ್ತಿದೆ...",
    "voiceListeningDesc": "ಮಾತನಾಡಲು ಪ್ರಾರಂಭಿಸಿ",
    "voiceError": "ದೋಷ",
    "voiceMicError": "ಮೈಕ್ರೊಫೋನ್ ಪ್ರವೇಶ ಸಿಗಲಿಲ್ಲ",
    "voiceProcessError": "ಆಡಿಯೋ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ದೋಷ",
    "voiceStop": "ನಿಲ್ಲಿಸಿ",
    "voiceYouSaid": "ನೀವು ಹೇಳಿದ್ದು",
    "voiceAssistantReply": "ಸಹಾಯಕನ ಉತ್ತರ",
    "voiceAssistantDesc": "ಮೈಕ್ರೊಫೋನ್ ಬಟನ್ ಒತ್ತಿ ನಿಮ್ಮ ಧಾನ್ಯ ಸಂಗ್ರಹಣೆ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ",
    
    // Alerts
    "alerts.title": "ಎಚ್ಚರಿಕೆಗಳು",
    "alerts.subtitle": "ಇತ್ತೀಚಿನ ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು",
    "alerts.no_alerts": "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
    "alerts.type.info": "ಮಾಹಿತಿ",
    "alerts.type.warning": "ಎಚ್ಚರಿಕೆ",
    "alerts.type.danger": "ಅಪಾಯ",
    "alerts.type.prediction": "AI ಮುನ್ಸೂಚನೆ",
    
    // Analytics
    "analytics.title": "ವಿಶ್ಲೇಷಣೆ",
    "analytics.subtitle": "ಐತಿಹಾಸಿಕ ದತ್ತಾಂಶ ಮತ್ತು ಪ್ರವೃತ್ತಿಗಳು",
    "analytics.temp_humidity": "ತಾಪಮಾನ ಮತ್ತು ತೇವಾಂಶ",
    "analytics.temp_humidity.desc": "ಕಳೆದ 24 ಗಂಟೆಗಳು",
    "analytics.gas": "ಅನಿಲ ಮಟ್ಟಗಳು",
    "analytics.gas.desc": "ಮಿಲಿಯನ್‌ಗೆ ಭಾಗಗಳು (ಪಿಪಿಎಂ)",
    "analytics.vibration": "ಕಂಪನ ಚಟುವಟಿಕೆ",
    "analytics.vibration.desc": "ಚಲನೆ ಪತ್ತೆ",
    
    // Prediction
    "prediction.title": "AI-ಚಾಲಿತ ಹಾಳಾಗುವ ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ",
    "prediction.subtitle": "ಧಾನ್ಯ ಗುಣಮಟ್ಟಕ್ಕಾಗಿ ಮುನ್ಸೂಚಕ ವಿಶ್ಲೇಷಣೆ",
    "prediction.confidence": "ವಿಶ್ವಾಸ",
    "prediction.risk": "ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ",
    "prediction.risk.low": "ಕಡಿಮೆ ಅಪಾಯ",
    "prediction.risk.medium": "ಮಧ್ಯಮ ಅಪಾಯ",
    "prediction.risk.high": "ಹೆಚ್ಚಿನ ಅಪಾಯ",
    "prediction.factors": "ಪ್ರಮುಖ ಕೊಡುಗೆ ಅಂಶಗಳು",
    "prediction.actions": "ಶಿಫಾರಸು ಮಾಡಲಾದ ಕ್ರಮಗಳು",
    "prediction.action.inspect": "ಸಂಗ್ರಹಣೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
    "prediction.action.ventilate": "ವಾತಾಯನವನ್ನು ಹೆಚ್ಚಿಸಿ",
    "prediction.action.monitor": "ನಿಕಟವಾಗಿ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
    
    // Settings
    "settings.title": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "settings.subtitle": "ಮಿತಿಗಳು ಮತ್ತು ಅಧಿಸೂಚನೆಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ",
    "settings.thresholds": "ಸುರಕ್ಷತಾ ಮಿತಿಗಳು",
    "settings.temp.max": "ಗರಿಷ್ಠ ತಾಪಮಾನ (°C)",
    "settings.temp.min": "ಕನಿಷ್ಠ ತಾಪಮಾನ (°C)",
    "settings.temp.alert": "ತಾಪಮಾನವು ಈ ಮೌಲ್ಯವನ್ನು ಮೀರಿದಾಗ ಎಚ್ಚರಿಕೆ",
    "settings.humidity.max": "ಗರಿಷ್ಠ ತೇವಾಂಶ (%)",
    "settings.humidity.min": "ಕನಿಷ್ಠ ತೇವಾಂಶ (%)",
    "settings.gas.max": "ಗರಿಷ್ಠ ಅನಿಲ ಮಟ್ಟ (ಪಿಪಿಎಂ)",
    "settings.vibration.max": "ಗರಿಷ್ಠ ಕಂಪನ",
    "settings.notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "settings.notifications.push": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    "settings.notifications.push.desc": "ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
    "settings.notifications.voice": "ಧ್ವನಿ ಎಚ್ಚರಿಕೆಗಳು",
    "settings.notifications.voice.desc": "ನಿರ್ಣಾಯಕ ಎಚ್ಚರಿಕೆಗಳಿಗಾಗಿ ಆಡಿಯೋ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    "settings.notifications.sms": "SMS ಅಧಿಸೂಚನೆಗಳು",
    "settings.notifications.sms.desc": "ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳಿಗಾಗಿ ಪಠ್ಯ ಸಂದೇಶಗಳನ್ನು ಕಳುಹಿಸಿ",
    "settings.notifications.ai": "AI ಮುನ್ಸೂಚನೆ ಎಚ್ಚರಿಕೆಗಳು",
    "settings.notifications.ai.desc": "AI ಹಾಳಾಗುವ ಅಪಾಯವನ್ನು ಪತ್ತೆಹಚ್ಚಿದಾಗ ತಿಳಿಸಿ",
    "settings.connection": "ಸಂಪರ್ಕ",
    "settings.connection.type": "ಸಂಪರ್ಕ ಪ್ರಕಾರ",
    "settings.language": "ಭಾಷೆ",
    "settings.language.select": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "settings.save": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
    "settings.reset": "ಡೀಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸಿ",
    
    // Bluetooth
    "bluetooth.title": "ಬ್ಲೂಟೂತ್ ಸಂವೇದಕ",
    "bluetooth.scan": "ಸಂವೇದಕಗಳಿಗಾಗಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    "bluetooth.disconnect": "ಸಂಪರ್ಕ ಕಡಿತಗೊಳಿಸಿ",
    "bluetooth.status.searching": "ಸಂವೇದಕಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    "bluetooth.status.connected": "ಸಂಪರ್ಕಗೊಂಡಿದೆ",
    "bluetooth.status.disconnected": "ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ",
    "bluetooth.unsupported": "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಬ್ಲೂಟೂತ್ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ",
  },
  bn: {
    // Navigation
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.alerts": "সতর্কতা",
    "nav.analytics": "বিশ্লেষণ",
    "nav.prediction": "AI পূর্বাভাস",
    "nav.settings": "সেটিংস",
    
    // Dashboard
    "dashboard.title": "গ্রেইনগার্ড ড্যাশবোর্ড",
    "dashboard.subtitle": "শস্য সংরক্ষণ অবস্থার রিয়েল-টাইম পর্যবেক্ষণ",
    "dashboard.bluetooth.connected": "ব্লুটুথ সংযুক্ত",
    "dashboard.sensors.title": "সেন্সর রিডিং",
    "dashboard.status.overview": "অবস্থা সংক্ষিপ্ত বিবরণ",
    "dashboard.status.all_systems": "সমস্ত সিস্টেম চালু আছে",
    "dashboard.status.check_alerts": "বিস্তারিত জানার জন্য সতর্কতা চেক করুন",
    "dashboard.last_updated": "সর্বশেষ আপডেট",
    
    // Sensors
    "sensor.temperature": "তাপমাত্রা",
    "sensor.humidity": "আর্দ্রতা",
    "sensor.gas": "গ্যাস স্তর",
    "sensor.vibration": "কম্পন",
    "sensor.status.safe": "🟢 নিরাপদ",
    "sensor.status.warning": "🟡 সতর্কতা",
    "sensor.status.danger": "🔴 বিপদ",
    "sensor.temp.optimal": "সর্বোত্তম পরিসীমা",
    "sensor.temp.high": "থ্রেশহোল্ডের উপরে",
    "sensor.humidity.optimal": "সর্বোত্তম পরিসীমা",
    "sensor.humidity.high": "থ্রেশহোল্ডের উপরে",
    "sensor.gas.normal": "স্বাভাবিক স্তর",
    "sensor.gas.elevated": "উচ্চ স্তর সনাক্ত করা হয়েছে",
    "sensor.vibration.stable": "স্থিতিশীল",
    "sensor.vibration.detected": "ক্রিয়াকলাপ সনাক্ত করা হয়েছে",
    
    // Alerts
    "alerts.title": "সতর্কতা",
    "alerts.subtitle": "সাম্প্রতিক বিজ্ঞপ্তি এবং সতর্কতা",
    "alerts.no_alerts": "বর্তমানে কোনো সতর্কতা নেই",
    "alerts.type.info": "তথ্য",
    "alerts.type.warning": "সতর্কতা",
    "alerts.type.danger": "বিপদ",
    "alerts.type.prediction": "AI পূর্বাভাস",
    
    // Analytics
    "analytics.title": "বিশ্লেষণ",
    "analytics.subtitle": "ঐতিহাসিক ডেটা এবং প্রবণতা",
    "analytics.temp_humidity": "তাপমাত্রা এবং আর্দ্রতা",
    "analytics.temp_humidity.desc": "শেষ 24 ঘন্টা",
    "analytics.gas": "গ্যাস স্তর",
    "analytics.gas.desc": "প্রতি মিলিয়নে অংশ (পিপিএম)",
    "analytics.vibration": "কম্পন ক্রিয়াকলাপ",
    "analytics.vibration.desc": "গতিবিধি সনাক্তকরণ",
    
    // Prediction
    "prediction.title": "AI-চালিত নষ্ট হওয়ার ঝুঁকি বিশ্লেষণ",
    "prediction.subtitle": "শস্য মানের জন্য পূর্বাভাসমূলক বিশ্লেষণ",
    "prediction.confidence": "আস্থা",
    "prediction.risk": "ঝুঁকি মূল্যায়ন",
    "prediction.risk.low": "কম ঝুঁকি",
    "prediction.risk.medium": "মাঝারি ঝুঁকি",
    "prediction.risk.high": "উচ্চ ঝুঁকি",
    "prediction.factors": "মূল অবদানকারী কারণ",
    "prediction.actions": "সুপারিশকৃত ক্রিয়া",
    "prediction.action.inspect": "সংরক্ষণ পরিদর্শন করুন",
    "prediction.action.ventilate": "বায়ুচলাচল বাড়ান",
    "prediction.action.monitor": "ঘনিষ্ঠভাবে পর্যবেক্ষণ করুন",
    
    // Settings
    "settings.title": "সেটিংস",
    "settings.subtitle": "থ্রেশহোল্ড এবং বিজ্ঞপ্তি কনফিগার করুন",
    "settings.thresholds": "সুরক্ষা থ্রেশহোল্ড",
    "settings.temp.max": "সর্বোচ্চ তাপমাত্রা (°C)",
    "settings.temp.min": "সর্বনিম্ন তাপমাত্রা (°C)",
    "settings.temp.alert": "যখন তাপমাত্রা এই মান অতিক্রম করে তখন সতর্কতা",
    "settings.humidity.max": "সর্বোচ্চ আর্দ্রতা (%)",
    "settings.humidity.min": "সর্বনিম্ন আর্দ্রতা (%)",
    "settings.gas.max": "সর্বোচ্চ গ্যাস স্তর (পিপিএম)",
    "settings.vibration.max": "সর্বোচ্চ কম্পন",
    "settings.notifications": "বিজ্ঞপ্তি",
    "settings.notifications.push": "পুশ বিজ্ঞপ্তি",
    "settings.notifications.push.desc": "আপনার ডিভাইসে সতর্কতা পান",
    "settings.notifications.voice": "ভয়েস সতর্কতা",
    "settings.notifications.voice.desc": "গুরুত্বপূর্ণ সতর্কতার জন্য অডিও বিজ্ঞপ্তি সক্ষম করুন",
    "settings.notifications.sms": "SMS বিজ্ঞপ্তি",
    "settings.notifications.sms.desc": "জরুরি সতর্কতার জন্য টেক্সট বার্তা পাঠান",
    "settings.notifications.ai": "AI পূর্বাভাস সতর্কতা",
    "settings.notifications.ai.desc": "যখন AI নষ্ট হওয়ার ঝুঁকি সনাক্ত করে তখন জানান",
    "settings.connection": "সংযোগ",
    "settings.connection.type": "সংযোগ প্রকার",
    "settings.language": "ভাষা",
    "settings.language.select": "ভাষা নির্বাচন করুন",
    "settings.save": "সেটিংস সংরক্ষণ করুন",
    "settings.reset": "ডিফল্টে রিসেট করুন",
    
    // Bluetooth
    "bluetooth.title": "ব্লুটুথ সেন্সর",
    "bluetooth.scan": "সেন্সরগুলির জন্য স্কান করুন",
    "bluetooth.disconnect": "সংযোগ বিচ্ছিন্ন করুন",
    "bluetooth.status.searching": "সেন্সর খোঁজা হচ্ছে...",
    "bluetooth.status.connected": "সংযুক্ত",
    "bluetooth.status.disconnected": "সংযুক্ত নয়",
    "bluetooth.unsupported": "এই ব্রাউজারে ব্লুটুথ সমর্থিত নয়",
  },
};
